# Site Build Settings

# jekyll-paginate configuration
paginate:            10
url:                 https://roguerope.be
# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
#plugins:             [jekyll-paginate, jekyll-gzip, jekyll-compress-images, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-compress-images]
plugins:             [jekyll-paginate, jekyll-gzip,  jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-compress-images]

sass:
  sass_dir: assets/css
  style: :nested

# img optim
image_optim:
  pngout: false
  svgo: false
  verbose: false



# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Rogue Rope"
description:	       "Rope events in Ghent, Belgium"
author:              "HansF"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
  path: /pages/feed.xml